Repository ArcturusNavigation/all_seaing_vehicle, pull requests merged in 2025-03, with the labels that each got.

#221 Converted obstacle tracking to use transforms instead of odom message, much smoother now
  all_seaing_bringup/config/perception/color_label_mappings.yaml
  all_seaing_bringup/launch/sim.launch.py
  all_seaing_bringup/rviz/dashboard.rviz
  all_seaing_perception/all_seaing_perception/bbox_project_pcloud.cpp
  all_seaing_perception/all_seaing_perception/object_tracking_map.cpp
  all_seaing_perception/all_seaing_perception/object_tracking_map_euclidean.cpp
  all_seaing_perception/all_seaing_perception/yolov8_node.py
  all_seaing_perception/include/all_seaing_perception/object_tracking_map.hpp
  all_seaing_perception/include/all_seaing_perception/object_tracking_map_euclidean.hpp
  all_seaing_perception/launch/debug_obstacle_detection.launch.py
Labels: enhancement

#227 feat: add signal detection for speed challenge
  all_seaing_autonomy/all_seaing_autonomy/roboboat/speed_challenge.py
Labels: enhancement, theory, refactor

#230 Fixed my code in Jetson & fine-tuned stuff
  .gitignore
  all_seaing_bringup/config/perception/color_label_mappings.yaml
  all_seaing_bringup/config/perception/contour_matching_color_ranges.yaml
  all_seaing_bringup/config/perception/matching_weights.yaml
  all_seaing_bringup/launch/sim.launch.py
  all_seaing_perception/CMakeLists.txt
  all_seaing_perception/all_seaing_perception/bbox_project_pcloud.cpp
  all_seaing_perception/launch/debug_obstacle_detection.launch.py
Labels: bug

#236 Fixed yaml stuff for obstacle detection
  all_seaing_autonomy/all_seaing_autonomy/roboboat/follow_buoy_path.py
  all_seaing_bringup/config/perception/color_buoy_label_mappings.yaml
  all_seaing_bringup/config/perception/color_label_mappings.yaml
  all_seaing_bringup/launch/sim.launch.py
  all_seaing_bringup/launch/vehicle.launch.py
  all_seaing_perception/all_seaing_perception/yolov8_node.py
  all_seaing_perception/launch/debug_obstacle_detection.launch.py
Labels: bug
